"""Concise requirement catalogue for ISO/IEC 17025:2017 checklist navigation.

These are operational paraphrases, not reproduced standard text.
"""

ISO_SUBCLAUSES = {
    "4.1": (("4.1.1","Perform laboratory activities impartially."),("4.1.2","Management safeguards impartiality."),("4.1.3","Prevent commercial, financial or other pressures from compromising impartiality."),("4.1.4","Continually identify impartiality risks arising from activities and relationships."),("4.1.5","Demonstrate how identified impartiality risks are eliminated or minimized.")),
    "4.2": (("4.2.1","Use legally enforceable commitments to manage information obtained or created during laboratory activities."),("4.2.2","Notify the customer before publicly releasing information unless disclosure is legally prohibited."),("4.2.3","Protect customer information received from sources other than the customer."),("4.2.4","Require personnel and external parties acting for the laboratory to preserve confidentiality.")),
    "5": (("5.1","Maintain a legal identity accountable for laboratory activities."),("5.2","Identify management with overall laboratory responsibility."),("5.3","Define and document the range of laboratory activities claimed as conforming."),("5.4","Perform laboratory activities to this standard, customer and regulatory requirements at all locations."),("5.5","Define organization, responsibilities, authorities and documented procedures needed for consistency."),("5.6","Assign personnel with authority and resources to implement, maintain and improve the management system."),("5.7","Ensure management communicates system effectiveness and maintains integrity during changes.")),
    "6.1": (("6.1","Provide the personnel, facilities, equipment, systems and support services needed for laboratory activities."),),
    "6.2": (("6.2.1","Ensure internal and external personnel are impartial, competent and work within the management system."),("6.2.2","Document competence requirements for every role influencing laboratory results."),("6.2.3","Ensure personnel are competent for assigned activities and can evaluate significant deviations."),("6.2.4","Communicate each person's duties, responsibilities and authority."),("6.2.5","Maintain procedures and records for competence, selection, training, supervision, authorization and monitoring."),("6.2.6","Authorize personnel for specific methods, result evaluation, reporting and related technical activities.")),
    "6.3": (("6.3.1","Provide facilities and environmental conditions suitable for valid results."),("6.3.2","Document facility and environmental requirements."),("6.3.3","Monitor, control and record environmental conditions where they affect validity."),("6.3.4","Control access, contamination and incompatible activities within laboratory areas."),("6.3.5","Ensure facility and environmental requirements are met at external sites.")),
    "6.4": (("6.4.1","Provide access to equipment needed for correct laboratory performance."),("6.4.2","Control equipment used outside permanent laboratory control."),("6.4.3","Maintain procedures for equipment handling, transport, storage, use and planned maintenance."),("6.4.4","Verify equipment meets specified requirements before use or return to service."),("6.4.5","Ensure measuring equipment can achieve required accuracy or uncertainty."),("6.4.6","Calibrate equipment when accuracy or uncertainty affects result validity or traceability is required."),("6.4.7","Establish, review and adjust calibration programmes."),("6.4.8","Label or identify equipment calibration status and validity."),("6.4.9","Remove defective or suspect equipment from service and evaluate the effect on prior work."),("6.4.10","Perform intermediate checks where needed to maintain confidence."),("6.4.11","Keep reference values and correction factors current and correctly applied."),("6.4.12","Prevent unintended equipment adjustment that could invalidate results."),("6.4.13","Retain complete identity, verification, calibration, maintenance, damage and performance records.")),
    "6.5": (("6.5.1","Establish and maintain metrological traceability through a documented unbroken calibration chain."),("6.5.2","Ensure measurement results are traceable to SI units through competent calibration or certified reference values."),("6.5.3","Use appropriate references and evidence where SI traceability is not technically possible.")),
    "6.6": (("6.6.1","Use only suitable externally provided products and services affecting laboratory activities."),("6.6.2","Define criteria for requirements, evaluation, selection, monitoring, re-evaluation and acceptance."),("6.6.3","Communicate requirements to external providers before supply.")),
    "7.1": (("7.1.1","Review requests, tenders and contracts to confirm requirements, capability, methods and resources."),("7.1.2","Inform customers when a requested method is inappropriate or outdated."),("7.1.3","Define and agree the decision rule when conformity statements are requested."),("7.1.4","Resolve differences between request and contract before work begins."),("7.1.5","Inform the customer of deviations from the contract."),("7.1.6","Repeat contract review when work is amended and communicate changes."),("7.1.7","Cooperate with customers to clarify requests and monitor performance."),("7.1.8","Retain records of reviews, changes and pertinent customer discussions.")),
    "7.2": (("7.2.1.1","Use appropriate methods and procedures for all laboratory activities and data evaluation."),("7.2.1.2","Keep methods, instructions and reference data current and available."),("7.2.1.3","Use the latest valid method version unless inappropriate or impossible."),("7.2.1.4","Select and inform the customer of an appropriate method when none is specified."),("7.2.1.5","Verify the laboratory can properly perform a method before introducing it."),("7.2.1.6","Plan method development and periodically review progress using competent personnel."),("7.2.1.7","Document, justify, authorize and obtain customer acceptance for method deviations."),("7.2.2.1","Validate non-standard, laboratory-developed and modified methods for intended use."),("7.2.2.2","Revalidate methods when changes affect the original validation."),("7.2.2.3","Ensure validated performance characteristics meet customer and specified requirements."),("7.2.2.4","Retain the validation procedure, requirements, characteristics, results and validity statement.")),
    "7.3": (("7.3.1","Use a sampling plan and method where the laboratory performs sampling."),("7.3.2","Describe selection, sampling plan, preparation and treatment needed for valid results."),("7.3.3","Retain complete sampling data, conditions, location, personnel and deviations.")),
    "7.4": (("7.4.1","Protect items through transportation, receipt, handling, storage, retention and disposal or return."),("7.4.2","Uniquely identify test and calibration items throughout responsibility."),("7.4.3","Record item deviations and consult the customer where suitability is uncertain."),("7.4.4","Maintain, monitor and record specified item storage or conditioning conditions.")),
    "7.5": (("7.5.1","Retain sufficient technical records to reproduce activities, conditions, personnel and results."),("7.5.2","Trace amendments to previous data and retain original and changed information with responsible personnel.")),
    "7.6": (("7.6.1","Identify uncertainty contributions and include significant components using suitable analysis."),("7.6.2","Evaluate measurement uncertainty for calibrations, including the laboratory's own equipment calibrations."),("7.6.3","Evaluate or estimate uncertainty for testing using applicable principles and method knowledge.")),
    "7.7": (("7.7.1","Plan, review and record monitoring activities that demonstrate result validity."),("7.7.2","Compare performance with other laboratories through proficiency testing or interlaboratory comparisons where available and appropriate."),("7.7.3","Analyze monitoring data, control work and take action when criteria are not met.")),
    "7.8": (("7.8.1.1","Review and authorize results before release."),("7.8.1.2","Report results accurately, clearly, unambiguously and objectively."),("7.8.1.3","Use simplified reports only by agreement while retaining omitted information."),("7.8.2.1","Include required report identity, laboratory, customer, method, item, dates, results and authorization information."),("7.8.2.2","Identify responsibility for customer-supplied information and state limitations affecting validity."),("7.8.3.1","Include test-specific conditions, conformity statements, uncertainty and opinions where needed."),("7.8.3.2","Meet additional reporting requirements when responsible for sampling."),("7.8.4.1","Include calibration uncertainty, conditions, traceability and relevant before/after results."),("7.8.4.2","Report compliance with specifications where applicable."),("7.8.4.3","Do not recommend calibration intervals unless agreed with the customer."),("7.8.5","Include sampling date, identification, location, plan and factors affecting interpretation."),("7.8.6.1","Document and apply the agreed decision rule for conformity statements."),("7.8.6.2","Clearly identify the results, specifications and decision rule supporting conformity."),("7.8.7.1","Release opinions and interpretations only through authorized personnel with documented basis."),("7.8.7.2","Record verbal opinions and interpretations provided to customers."),("7.8.8.1","Clearly identify, justify and reference amended reports."),("7.8.8.2","Issue amendments as additional documents or complete replacements meeting reporting requirements.")),
    "7.9": (("7.9.1","Maintain a documented process to receive, evaluate and decide complaints."),("7.9.2","Make the complaint process available and confirm responsibility."),("7.9.3","Gather and verify information needed to validate complaints."),("7.9.4","Acknowledge complaints and provide progress and outcome reports where possible."),("7.9.5","Ensure complaint decisions are made or reviewed independently of the original work."),("7.9.6","Use external personnel where necessary to preserve independent review."),("7.9.7","Give formal notice when complaint handling is complete.")),
    "7.10": (("7.10.1","Control nonconforming work through responsibilities, risk-based actions, impact evaluation and customer notification."),("7.10.2","Retain records of nonconforming work and resulting actions."),("7.10.3","Initiate corrective action where recurrence or system conformity is in doubt.")),
    "7.11": (("7.11.1","Provide access to data and information needed for laboratory activities."),("7.11.2","Validate information systems before introduction and authorize and validate changes."),("7.11.3","Protect systems against unauthorized access, tampering, loss and unsuitable operating conditions."),("7.11.4","Ensure externally managed systems meet applicable requirements."),("7.11.5","Make relevant instructions and reference data readily available."),("7.11.6","Check calculations and data transfers systematically.")),
    "8.1": (("8.1.1","Establish, document, implement and maintain a management system supporting consistent conformity."),("8.1.2","Implement at least the management-system controls specified under Option A."),("8.1.3","Demonstrate an ISO 9001 system can consistently support fulfilment of this standard under Option B.")),
    "8.2": (("8.2.1","Establish and maintain policies and objectives addressing competence, impartiality and consistent operation."),("8.2.2","Ensure policies and objectives are understood and implemented throughout the laboratory."),("8.2.3","Demonstrate management commitment to system development and continual improvement."),("8.2.4","Reference all documentation, processes, systems and records needed for fulfilment."),("8.2.5","Provide personnel access to relevant management-system information.")),
    "8.3": (("8.3.1","Control internal and external documents related to fulfilment of the standard."),("8.3.2","Approve, review, update, identify, distribute and protect documents while preventing unintended use of obsolete versions.")),
    "8.4": (("8.4.1","Create and retain legible records demonstrating fulfilment of requirements."),("8.4.2","Control identification, storage, protection, backup, archive, retrieval, retention and disposal of records.")),
    "8.5": (("8.5.1","Consider risks and opportunities affecting intended results, objectives, impacts and improvement."),("8.5.2","Plan, integrate, implement and evaluate actions addressing risks and opportunities."),("8.5.3","Make actions proportionate to potential effects on result validity.")),
    "8.6": (("8.6.1","Identify and select opportunities for improvement and implement necessary actions."),("8.6.2","Seek and analyze customer feedback to improve systems, activities and service.")),
    "8.7": (("8.7.1","React to nonconformities, correct them, address consequences, analyze causes and verify action effectiveness."),("8.7.2","Make corrective actions appropriate to the effects of encountered nonconformities."),("8.7.3","Retain records of nonconformities, causes, actions and results.")),
    "8.8": (("8.8.1","Conduct planned internal audits covering conformity and effective implementation."),("8.8.2","Plan audit criteria and scope, select impartial auditors, report results, correct findings and retain records.")),
    "8.9": (("8.9.1","Review the management system at planned intervals for continuing suitability, adequacy and effectiveness."),("8.9.2","Record required review inputs including changes, objectives, audits, complaints, resources, risks and result validity."),("8.9.3","Record decisions and actions concerning effectiveness, improvement, resources and necessary changes.")),
}


def subclauses_for(parent_code):
    return ISO_SUBCLAUSES.get(parent_code, ())
